### ISSUE TITLE
great but there are some issues

### ISSUE THREAD

**Issue by idealerror** [electrikhq/electrik#12]
Hello,

This is a great starter for building a SaaS with Laravel, however I've found some issues:

- There are a lot of hardcoded mentions of India vs. US for subscriptions, this doesn't scale well, specifically around the TAX RATES where if you select US and don't update the tax rates in the .env, there are errors.  
- Maybe detail which .env variables are required (STRIPE keys are required prior to registration/login, tax rates must be defined or it errors when you subscribe)
- logout route is missing
- if you have select a free plan with 0 trial days, it still asks for a credit card to register
- postal code is labeled as "pincode" in the registration, I think this is incorrect?
- on /teams/roles, it references `display_name` in the `roles` table, but this column doesn't exist
- on /teams/members you see all users as part of one team, even though they have separate teams.  You probably need to add `filters()` to the Livewire Datatable
- all subscriptions are labeled as "sprrw", no idea why?  This is also hardcoded into the views `@if(!auth()->user()->currentTeam->subscribed('sprrw'))`

This is all I found on the first pass, but it's a start :)

**Comment by neerajsohal** [comment]
Hey @idealerror,

Thanks a lot for testing and finding issues. I really wanted someone to do this as I have contracted "feature blindness" :)

These issues are a good start for a production release prep. Although, there is another issue already listed for Tax support. It's a little tricky to make it dynamic. Some intervention would be required from the developer's end. I will add this to the documentation as well.

**Comment by neerajsohal** [comment]
@idealerror 

Sorry, it took quite some time to close this issue. I got busy with another project and some of these needed code rewrites. 

Have checked and closed all the items listed in the issue. 

Again thanks a lot for taking the time out and helping me with the feedback. I greatly appreciate it.
