### ISSUE TITLE
Problem Running Migrations. (Cannot declare class TeamworkSetupTables, because the name is already in use)

### ISSUE THREAD

**Issue by MusheAbdulHakim** [electrikhq/electrik#13]
I can't run migrations because apparently some of the files have the same class name.
**database/migrations/2023_01_07_203947_teamwork_setup_tables.php:6** and **database/migrations/2023_01_07_203242_teamwork_setup_tables.php**

**Comment by mardillu** [comment]
@MusheAbdulHakim 
It appears running the `php artisan electrik:install` command more than once causes the migration files to be duplicated, hence you get that error during the install.

One solutions is to start the installation over. At least, in my that solved the issue

**Comment by MusheAbdulHakim** [comment]
Thanks. That worked.

**Comment by neerajsohal** [comment]
Hi, @MusheAbdulHakim. The install command needs to be run only once. If you run it again it'll create problems with duplicate migration files. Let me think of a way to warn users if they try to re-run the install command.
