### ISSUE TITLE
if you have select a free plan with 0 trial days, it still asks for a credit card to register

### ISSUE THREAD

**Issue by neerajsohal** [electrikhq/electrik#18]
Need to give user an option to configure this behaviour in the config file. My view is that some SaaS require credit card details even if someone subscribes to a free plan.

**Comment by yordadev** [comment]
I like the idea of a configuration file option for this. Having free users provide a CC is generally a good idea to prevent resource abuse, however not everyone wants this option enabled and just want free subscriptions.

**Comment by neerajsohal** [comment]
I agree. I'll make it optional via the config file.

**Comment by neerajsohal** [comment]
Have made electrik.php configuration file which can be used for defining whether to charge users for free plans or not.
