### ISSUE TITLE
git checkout in windows fails because YAML filename ends in space

### ISSUE THREAD

**Issue by Mohtashim-kamal** [electrikhq/electrik#24]
Install of electrik/electrik failed

In GitDownloader.php line 500:

  Failed to execute git checkout 99dc6b3e5ec379c6a93f24b289c5eeff6438f8fe -- && git reset --hard 99dc6b3e5ec379c6a93f
  24b289c5eeff6438f8fe --

  error: invalid path '.scrutinizer.yml '

-Getting the above-mentioned error, please remove the space at the end of ".scrutinizer.yml" file because windows do not normally permit trailing spaces in a directory or file name.

**Comment by neerajsohal** [comment]
Let me get it checked. Can you also share the windows version and git version? It will help me replicate the error on my local system.

**Comment by Mohtashim-kamal** [comment]
Window 10 and Git version is 2.40.0

**Comment by Mohtashim-kamal** [comment]
Windows 10 version 22H2 and Git version is 2.40.0

**Comment by neerajsohal** [comment]
Hey,

Have changed the file name. It was my bad! Can you try once with version v0.0.13 (6de59a21c477044596d656a0cc3f68fe4a2a97ff).

Cheers!
