### ISSUE TITLE
Strandardise Stripe's Tax support

### ISSUE THREAD

**Issue by neerajsohal** [electrikhq/electrik#3]

**Comment by pablotransifex** [comment]
Is this issue related with this error after registration?

`Stripe
 \ 
Exception
 \ 
InvalidRequestException
PHP 8.2.1
9.46.0

You passed an empty string for 'default_tax_rates[0]'. We assume empty values are an attempt to unset a parameter; however 'default_tax_rates[0]' cannot be unset. You should remove 'default_tax_rates[0]' from your request or supply a non-empty value.`

**Comment by sanchezpablo** [comment]
Is this issue related with this error after registration?

```
Stripe Exception InvalidRequestException PHP 8.2.1 9.46.0

You passed an empty string for 'default_tax_rates[0]'. We assume empty values are an attempt to unset a parameter; however 'default_tax_rates[0]' cannot be unset. You should remove 'default_tax_rates[0]' from your request or supply a non-empty value.
```

**Comment by sanchezpablo** [comment]
I used the .env variable `CASHIER_TAX_RATE_SGST` and the other variables to map with a Stripe tax rate, and seems to worked ok.

**Comment by neerajsohal** [comment]
Glad to hear that. Closing the issue. Feel free to open again or create a new issue.
