### ISSUE TITLE
Problem with required illuminate/support dependency

### ISSUE THREAD

**Issue by noverkill** [electrikhq/electrik#32]
Tried to install your package with Laravel 9 and got the below error when running composer require electrik/electrik:
  Problem 1
    - electrik/electrik[2.0.0, ..., 2.0.5] require illuminate/support ^10.10 -> found illuminate/support[v10.10.0, ..., v10.24.0] but these were not loaded, likely because it conflicts with another require.

Then I found out that the problem most probable the below:
Only one of these can be installed: laravel/framework[v9.19.0, ..., v9.52.15], illuminate/support[v10.10.0, ..., v10.24.0]. laravel/framework replaces illuminate/support and thus cannot coexist with it.

Laravel/framework replaces illuminate/support and thus cannot coexist with it.
I think you might need to fix this in your composer.json and require the appropriate laravel/framework version instead of illuminate/support.
]

**Comment by neerajsohal** [comment]
Thanks for pointing out. I'll take a look.

**Comment by neerajsohal** [comment]
This was solved in #34. Closing in favour of #35.
